/*
 * File: app/store/Hours.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HoursLogger.store.Hours', {
    extend: 'Ext.data.Store',

    requires: [
        'HoursLogger.model.Hours',
        'Ext.data.proxy.LocalStorage'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Hours',
            model: 'HoursLogger.model.Hours',
            data: [
                {
                    start: '2019-05-09 11:15',
                    stop: '2019-05-09 11:30',
                    duration: 0.25,
                    comment: 'qwery'
                },
                {
                    start: 'eum',
                    stop: 'dolor',
                    duration: 888.57,
                    comment: 'necessitatibus'
                },
                {
                    start: '2019-05-05 15:15',
                    stop: '2019-05-05 18:00',
                    duration: 2.75,
                    comment: 'ut'
                },
                {
                    start: 'voluptatum',
                    stop: 'adipisci',
                    duration: 455.29,
                    comment: 'et'
                },
                {
                    start: 'rem',
                    stop: 'quia',
                    duration: 917.67,
                    comment: 'enim'
                },
                {
                    start: 'cupiditate',
                    stop: 'molestiae',
                    duration: 318.27,
                    comment: 'explicabo'
                },
                {
                    start: '2019-05-09 15:15',
                    stop: '2019-05-09 16:30',
                    duration: 1.25,
                    comment: 'sit'
                },
                {
                    start: 'ut',
                    stop: 'ullam',
                    duration: 838.61,
                    comment: 'sapiente'
                },
                {
                    start: 'quis',
                    stop: 'corporis',
                    duration: 574.95,
                    comment: 'eaque'
                },
                {
                    start: 'reiciendis',
                    stop: 'repellendus',
                    duration: 327.73,
                    comment: 'non'
                },
                {
                    start: 'quod',
                    stop: 'dolor',
                    duration: 479.31,
                    comment: 'quas'
                },
                {
                    start: 'non',
                    stop: 'odio',
                    duration: 115.93,
                    comment: 'debitis'
                },
                {
                    start: 'quasi',
                    stop: 'rerum',
                    duration: 350.38,
                    comment: 'ratione'
                },
                {
                    start: 'non',
                    stop: 'expedita',
                    duration: 493.24,
                    comment: 'earum'
                },
                {
                    start: 'repellendus',
                    stop: 'autem',
                    duration: 192.01,
                    comment: 'sed'
                },
                {
                    start: 'quia',
                    stop: 'rerum',
                    duration: 959.03,
                    comment: 'iure'
                },
                {
                    start: 'eos',
                    stop: 'reiciendis',
                    duration: 662.26,
                    comment: 'est'
                },
                {
                    start: 'libero',
                    stop: 'dolores',
                    duration: 735.06,
                    comment: 'et'
                },
                {
                    start: 'est',
                    stop: 'magni',
                    duration: 537.78,
                    comment: 'omnis'
                },
                {
                    start: 'praesentium',
                    stop: 'numquam',
                    duration: 630.64,
                    comment: 'hic'
                },
                {
                    start: 'placeat',
                    stop: 'minus',
                    duration: 630.53,
                    comment: 'nesciunt'
                },
                {
                    start: 'doloremque',
                    stop: 'delectus',
                    duration: 332.47,
                    comment: 'voluptatem'
                },
                {
                    start: 'ea',
                    stop: 'sed',
                    duration: 805.41,
                    comment: 'suscipit'
                },
                {
                    start: 'dignissimos',
                    stop: 'asperiores',
                    duration: 137.28,
                    comment: 'quis'
                },
                {
                    start: 'distinctio',
                    stop: 'possimus',
                    duration: 11.09,
                    comment: 'consectetur'
                },
                {
                    start: 'nulla',
                    stop: 'est',
                    duration: 280.12,
                    comment: 'sit'
                },
                {
                    start: 'ipsam',
                    stop: 'temporibus',
                    duration: 105.45,
                    comment: 'natus'
                },
                {
                    start: 'ipsum',
                    stop: 'sed',
                    duration: 679.41,
                    comment: 'ducimus'
                },
                {
                    start: 'occaecati',
                    stop: 'ab',
                    duration: 402.79,
                    comment: 'harum'
                },
                {
                    start: 'nam',
                    stop: 'ullam',
                    duration: 95.3,
                    comment: 'magni'
                }
            ],
            proxy: {
                type: 'localstorage'
            }
        }, cfg)]);
    }
});