/*
 * File: app/store/Hours.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HoursLogger.store.Hours', {
    extend: 'Ext.data.Store',

    requires: [
        'HoursLogger.model.Hours',
        'Ext.data.proxy.LocalStorage'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Hours',
            model: 'HoursLogger.model.Hours',
            data: [
                {
                    start: '2019-05-09 11:15',
                    stop: '2019-05-09 11:30',
                    duration: 0.25,
                    comment: 'qwery'
                },
                {
                    start: '2019-05-05 15:15',
                    stop: '2019-05-05 18:00',
                    duration: 2.75,
                    comment: 'ut'
                },
                {
                    start: '2019-05-09 15:15',
                    stop: '2019-05-09 16:30',
                    duration: 1.25,
                    comment: 'sit'
                }
            ],
            proxy: {
                type: 'localstorage'
            }
        }, cfg)]);
    }
});