/*
 * File: app/view/MainViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HoursLogger.view.MainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main',

    onAddHoursButtonTap: function(button, e, eOpts) {
        var panel = Ext.create({
            xtype: 'registerupdateform',
            centered: true,
            fullscreen: true,
            modal: true
        });
        panel.show();
    },

    onSubtractDayTap: function(button, e, eOpts) {
        var label = Ext.getCmp('dateLabel');
        var date = Ext.Date.add(new Date(label.getHtml()), Ext.Date.DAY, -1);
        label.setHtml(Ext.Date.format(date, 'Y-m-d'));
    },

    onAddDayTap: function(button, e, eOpts) {
        var label = Ext.getCmp('dateLabel');
        var date = Ext.Date.add(new Date(label.getHtml()), Ext.Date.DAY, 1);
        label.setHtml(Ext.Date.format(date, 'Y-m-d'));
    },

    onItemSelected: function(sender, record) {
        alert(record);
        Ext.create({
            xtype: 'registerupdateform',
            centered: true,
            fullscreen: true,
            modal: true,
            record: record // Sender record som skal fylles inn i FormPanel
        }).show();
        sender.deselect(record);
    }

});