/*
 * File: app/view/RegisterUpdateFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HoursLogger.view.RegisterUpdateFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.registerupdateform',

    requires: [
        'HoursLogger.store.Hours'
    ],

    updateDuration: function() {
        var start = Ext.getCmp("regUpdStartField").getValue();
        var stop = Ext.getCmp("regUpdStopField").getValue();

        var dStart = new Date(start);
        if(start !== null && start !== ""){
            Ext.getCmp("regUpdStartField").setValue(Ext.Date.format(dStart, 'C'));
        }

        var dStop = new Date(stop);
        if(stop !== null && stop !== ""){
            Ext.getCmp("regUpdStopField").setValue(Ext.Date.format(dStop, 'C'));
        }

        if(start !== null && start !== "" &&
           stop !== null && stop !== "" ){
            Ext.getCmp("regUpdDurationField").setValue(Ext.Date.diff(dStart, dStop, Ext.Date.MINUTE)/60);
        }
    },

    onRegUpdStartFieldFocusleave: function(component, event, eOpts) {
        this.updateDuration();
    },

    onRegUpdStopFieldFocusleave: function(component, event, eOpts) {
        this.updateDuration();
    },

    /*  */
    onRegUpdDurationFieldFocusleave: function(component, event, eOpts) {
        var start = Ext.getCmp("regUpdStartField").getValue();
        var dStart = new Date(start);
        var duration = Ext.getCmp("regUpdDurationField").getValue();
        if(start !== null && start !== "" &&
        duration !== null && duration !== "" ){
            Ext.getCmp("regUpdStopField").setValue(Ext.Date.format(Ext.Date.add(dStart, Ext.Date.HOUR, duration), 'C'));
        }
    },

    submitUpdate: function(button, e, eOpts) {
        var store= Ext.getStore("Hours");
        var start = Ext.getCmp("regUpdStartField").getValue();
        var stop = Ext.getCmp("regUpdStopField").getValue();
        var duration = Ext.getCmp("regUpdDurationField").getValue();
        var comment= Ext.getCmp("regUpdCommentField").getValue();

        var view = this.getView();
        record = view.getRecord();
        if(record !== null){
            record.set('start', start);
            record.set('stop', stop);
            record.set('duration', duration);
            record.set('comment', comment);
            record.commit();

        } else {
            var store= Ext.getStore("Hours");
            var timeFormat={
                start: start,
                stop: stop,
                duration: duration,
                comment: comment
            };
            store.add(timeFormat);
            store.sync();
        }

        view.destroy();
    },

    cancelUpdate: function(button, e, eOpts) {
        var view = this.getView(),
            record = view.getRecord();
        view.destroy();
        record.reject();
    },

    onFormpanelInitialize: function(component, eOpts) {
        var record = component.getRecord();
        if (record !== null) {
            Ext.getCmp("regUpdStartField").setValue(record.data.start);
            Ext.getCmp("regUpdStopField").setValue(record.data.stop);
            Ext.getCmp("regUpdDurationField").setValue(record.data.duration);
            Ext.getCmp("regUpdCommentField").setValue(record.data.comment);

        }
    }

});